apiVersion: v1
kind: Pod
metadata:
  name: ruthenium
  labels:
    app.kubernetes.io/name: ruthenium
spec:
  containers:
  - name: node
    imagePullPolicy: Always
    image: {{ .Values.image }}
    ports:
    - containerPort: 8106
    command: ["/app/node"]
    args: 
    - "-public-key={{ .Values.publicKey }}"
    - "-private-key={{ .Values.privateKey }}"
  - name: ui
    imagePullPolicy: Always
    image: {{ .Values.image }}
    ports:
    - containerPort: 8080
    command: ["/app/ui"]
    args: 
    - "-public-key={{ .Values.publicKey }}"
    - "-private-key={{ .Values.privateKey }}"
    - "-templates-path={{ .Values.templatesPath }}"
  imagePullSecrets: {{ range .Values.imagePullSecrets }}
    - {{ . }}
  {{ end }}  
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - amd64

---
apiVersion: v1
kind: Service
metadata:
  name: ruthenium
spec:
  selector:
    app.kubernetes.io/name: ruthenium
  ports:
    - name: node
      protocol: TCP
      port: 8106
      targetPort: 8106
    - name: ui
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
