{{ if not ( eq .Values.app.type "job" ) }}
---
{{- $chartName := .Chart.Name -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $chartName }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0
    nginx.org/location-snippets: |
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-Port 443;
spec:
  rules:
    - host: {{ .Values.url.prefix }}.{{ .Values.url.domainOverride | default .Values.global.domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $chartName }}
              servicePort: 80
  {{- range .Values.url.serverAlias }}
  - host: {{ . }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $chartName }}
          servicePort: 80
  {{- end }}

{{ end }}
