{{- $values := .Values -}}
{{- range $secret := .Values.secrets -}}
apiVersion: v1
kind: Secret

metadata:
  name: {{ $secret.name }}
  namespace: {{ $secret.namespace | default "default" }}
  annotations:
{{- range $k, $v := $secret.annotations }}
    {{ $k }}: {{ $v |quote}}
{{- end }}
{{- if hasKey $secret "data" }}
data:
{{- range $k, $v := $secret.data }}
  {{ $k }}: {{ $v }}
{{- end }}
{{- end }}
{{- if hasKey $secret "stringData" }}
stringData:
  {{- toYaml $secret.stringData | nindent 2 }}
{{- end }}
type: {{ $secret.type |default "Opaque" | quote}}
{{- end -}}