---
image: golang:1.8-alpine
include:
  - project: coinsmaster/common/pipeline-manifests
    file: container-build-manifest.yaml

stages:
  - test
  - build
  - scan

before_script:
  - mkdir -p /go/src/gitlab.com
  - ln -s /builds/coinsmaster /go/src/gitlab.com/coinsmaster
coverage:
  stage: test
  script:
    - apk add --no-cache git build-base
    - cd /go/src/gitlab.com/coinsmaster/ruthenium
    - go get ./...
    - go test -v ./test/...

build:
  stage: build
  extends: .container_kaniko_build

scan:
  stage: scan
  extends: .docker_kaniko_trivy
