---
image: golang:1.8-alpine
include:
  - project: coinsmaster/common/pipeline-manifests
    file: container-build-manifest.yaml


stages:
  - build
  - scan
  - test

build:
  stage: build
  extends: .container_kaniko_build

scan:
  stage: scan
  extends: .docker_kaniko_trivy

test:
  stage: test
  needs:
    - build
  script:
    - go test -v ./app/test/...
