---
image: golang:latest
include:
  - project: coinsmaster/common/pipeline-manifests
    file: container-build-manifest.yaml

stages:
  - test
  - build
  - scan

test:
  stage: test
  script:
    - cd /go/src/gitlab.com/coinsmaster/ruthenium
    - go get ./...
    - go test -v ./test/...

build:
  stage: build
  extends: .container_kaniko_build

scan:
  stage: scan
  extends: .docker_kaniko_trivy
