// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package verification

import (
	"sync"
)

// Ensure, that HumansManagerMock does implement HumansManager.
// If this is not the case, regenerate this file with moq.
var _ HumansManager = &HumansManagerMock{}

// HumansManagerMock is a mock implementation of HumansManager.
//
//	func TestSomethingThatUsesHumansManager(t *testing.T) {
//
//		// make and configure a mocked HumansManager
//		mockedHumansManager := &HumansManagerMock{
//			IsRegisteredFunc: func(address string) (bool, error) {
//				panic("mock out the IsRegistered method")
//			},
//		}
//
//		// use mockedHumansManager in code that requires HumansManager
//		// and then make assertions.
//
//	}
type HumansManagerMock struct {
	// IsRegisteredFunc mocks the IsRegistered method.
	IsRegisteredFunc func(address string) (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// IsRegistered holds details about calls to the IsRegistered method.
		IsRegistered []struct {
			// Address is the address argument value.
			Address string
		}
	}
	lockIsRegistered sync.RWMutex
}

// IsRegistered calls IsRegisteredFunc.
func (mock *HumansManagerMock) IsRegistered(address string) (bool, error) {
	if mock.IsRegisteredFunc == nil {
		panic("HumansManagerMock.IsRegisteredFunc: method is nil but HumansManager.IsRegistered was just called")
	}
	callInfo := struct {
		Address string
	}{
		Address: address,
	}
	mock.lockIsRegistered.Lock()
	mock.calls.IsRegistered = append(mock.calls.IsRegistered, callInfo)
	mock.lockIsRegistered.Unlock()
	return mock.IsRegisteredFunc(address)
}

// IsRegisteredCalls gets all the calls that were made to IsRegistered.
// Check the length with:
//
//	len(mockedHumansManager.IsRegisteredCalls())
func (mock *HumansManagerMock) IsRegisteredCalls() []struct {
	Address string
} {
	var calls []struct {
		Address string
	}
	mock.lockIsRegistered.RLock()
	calls = mock.calls.IsRegistered
	mock.lockIsRegistered.RUnlock()
	return calls
}
