// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package network

import (
	"github.com/my-cloud/ruthenium/src/api/connection"
	"sync"
)

// Ensure, that SenderProviderMock does implement SenderProvider.
// If this is not the case, regenerate this file with moq.
var _ connection.SenderProvider = &SenderProviderMock{}

// SenderProviderMock is a mock implementation of SenderProvider.
//
// 	func TestSomethingThatUsesSenderProvider(t *testing.T) {
//
// 		// make and configure a mocked SenderProvider
// 		mockedSenderProvider := &SenderProviderMock{
// 			CreateSenderFunc: func(ip string, port uint16, target string) (Sender, error) {
// 				panic("mock out the CreateSender method")
// 			},
// 		}
//
// 		// use mockedSenderProvider in code that requires SenderProvider
// 		// and then make assertions.
//
// 	}
type SenderProviderMock struct {
	// CreateSenderFunc mocks the CreateSender method.
	CreateSenderFunc func(ip string, port uint16, target string) (connection.Sender, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateSender holds details about calls to the CreateSender method.
		CreateSender []struct {
			// IP is the ip argument value.
			IP string
			// Port is the port argument value.
			Port uint16
			// Target is the target argument value.
			Target string
		}
	}
	lockCreateSender sync.RWMutex
}

// CreateSender calls CreateSenderFunc.
func (mock *SenderProviderMock) CreateSender(ip string, port uint16, target string) (connection.Sender, error) {
	if mock.CreateSenderFunc == nil {
		panic("SenderProviderMock.CreateSenderFunc: method is nil but SenderProvider.CreateSender was just called")
	}
	callInfo := struct {
		IP     string
		Port   uint16
		Target string
	}{
		IP:     ip,
		Port:   port,
		Target: target,
	}
	mock.lockCreateSender.Lock()
	mock.calls.CreateSender = append(mock.calls.CreateSender, callInfo)
	mock.lockCreateSender.Unlock()
	return mock.CreateSenderFunc(ip, port, target)
}

// CreateSenderCalls gets all the calls that were made to CreateSender.
// Check the length with:
//     len(mockedSenderProvider.CreateSenderCalls())
func (mock *SenderProviderMock) CreateSenderCalls() []struct {
	IP     string
	Port   uint16
	Target string
} {
	var calls []struct {
		IP     string
		Port   uint16
		Target string
	}
	mock.lockCreateSender.RLock()
	calls = mock.calls.CreateSender
	mock.lockCreateSender.RUnlock()
	return calls
}
