// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package network

import (
	p2p "github.com/leprosus/golang-p2p"
	"github.com/my-cloud/ruthenium/src/api/connection"
	"sync"
)

// Ensure, that ServableMock does implement Servable.
// If this is not the case, regenerate this file with moq.
var _ connection.Servable = &ServableMock{}

// ServableMock is a mock implementation of Servable.
//
// 	func TestSomethingThatUsesServable(t *testing.T) {
//
// 		// make and configure a mocked Servable
// 		mockedServable := &ServableMock{
// 			ServeFunc: func() error {
// 				panic("mock out the Serve method")
// 			},
// 			SetHandleFunc: func(topic string, handler p2p.Handler)  {
// 				panic("mock out the SetHandle method")
// 			},
// 		}
//
// 		// use mockedServable in code that requires Servable
// 		// and then make assertions.
//
// 	}
type ServableMock struct {
	// ServeFunc mocks the Serve method.
	ServeFunc func() error

	// SetHandleFunc mocks the SetHandle method.
	SetHandleFunc func(topic string, handler p2p.Handler)

	// calls tracks calls to the methods.
	calls struct {
		// Serve holds details about calls to the Serve method.
		Serve []struct {
		}
		// SetHandle holds details about calls to the SetHandle method.
		SetHandle []struct {
			// Topic is the topic argument value.
			Topic string
			// Handler is the handler argument value.
			Handler p2p.Handler
		}
	}
	lockServe     sync.RWMutex
	lockSetHandle sync.RWMutex
}

// Serve calls ServeFunc.
func (mock *ServableMock) Serve() error {
	if mock.ServeFunc == nil {
		panic("ServableMock.ServeFunc: method is nil but Servable.Serve was just called")
	}
	callInfo := struct {
	}{}
	mock.lockServe.Lock()
	mock.calls.Serve = append(mock.calls.Serve, callInfo)
	mock.lockServe.Unlock()
	return mock.ServeFunc()
}

// ServeCalls gets all the calls that were made to Serve.
// Check the length with:
//     len(mockedServable.ServeCalls())
func (mock *ServableMock) ServeCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockServe.RLock()
	calls = mock.calls.Serve
	mock.lockServe.RUnlock()
	return calls
}

// SetHandle calls SetHandleFunc.
func (mock *ServableMock) SetHandle(topic string, handler p2p.Handler) {
	if mock.SetHandleFunc == nil {
		panic("ServableMock.SetHandleFunc: method is nil but Servable.SetHandle was just called")
	}
	callInfo := struct {
		Topic   string
		Handler p2p.Handler
	}{
		Topic:   topic,
		Handler: handler,
	}
	mock.lockSetHandle.Lock()
	mock.calls.SetHandle = append(mock.calls.SetHandle, callInfo)
	mock.lockSetHandle.Unlock()
	mock.SetHandleFunc(topic, handler)
}

// SetHandleCalls gets all the calls that were made to SetHandle.
// Check the length with:
//     len(mockedServable.SetHandleCalls())
func (mock *ServableMock) SetHandleCalls() []struct {
	Topic   string
	Handler p2p.Handler
} {
	var calls []struct {
		Topic   string
		Handler p2p.Handler
	}
	mock.lockSetHandle.RLock()
	calls = mock.calls.SetHandle
	mock.lockSetHandle.RUnlock()
	return calls
}
