// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package presentation

import (
	"sync"
)

// Ensure, that NeighborCallerMock does implement NeighborCaller.
// If this is not the case, regenerate this file with moq.
var _ NeighborCaller = &NeighborCallerMock{}

// NeighborCallerMock is a mock implementation of NeighborCaller.
//
//	func TestSomethingThatUsesNeighborCaller(t *testing.T) {
//
//		// make and configure a mocked NeighborCaller
//		mockedNeighborCaller := &NeighborCallerMock{
//			AddTransactionFunc: func(transaction []byte) error {
//				panic("mock out the AddTransaction method")
//			},
//			GetBlocksFunc: func(startingBlockHeight uint64) ([]byte, error) {
//				panic("mock out the GetBlocks method")
//			},
//			GetFirstBlockTimestampFunc: func() (int64, error) {
//				panic("mock out the GetFirstBlockTimestamp method")
//			},
//			GetSettingsFunc: func() ([]byte, error) {
//				panic("mock out the GetSettings method")
//			},
//			GetTransactionsFunc: func() ([]byte, error) {
//				panic("mock out the GetTransactions method")
//			},
//			GetUtxosFunc: func(address string) ([]byte, error) {
//				panic("mock out the GetUtxos method")
//			},
//			SendTargetsFunc: func(targets []string) error {
//				panic("mock out the SendTargets method")
//			},
//			TargetFunc: func() string {
//				panic("mock out the Target method")
//			},
//		}
//
//		// use mockedNeighborCaller in code that requires NeighborCaller
//		// and then make assertions.
//
//	}
type NeighborCallerMock struct {
	// AddTransactionFunc mocks the AddTransaction method.
	AddTransactionFunc func(transaction []byte) error

	// GetBlocksFunc mocks the GetBlocks method.
	GetBlocksFunc func(startingBlockHeight uint64) ([]byte, error)

	// GetFirstBlockTimestampFunc mocks the GetFirstBlockTimestamp method.
	GetFirstBlockTimestampFunc func() (int64, error)

	// GetSettingsFunc mocks the GetSettings method.
	GetSettingsFunc func() ([]byte, error)

	// GetTransactionsFunc mocks the GetTransactions method.
	GetTransactionsFunc func() ([]byte, error)

	// GetUtxosFunc mocks the GetUtxos method.
	GetUtxosFunc func(address string) ([]byte, error)

	// SendTargetsFunc mocks the SendTargets method.
	SendTargetsFunc func(targets []string) error

	// TargetFunc mocks the Target method.
	TargetFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// AddTransaction holds details about calls to the AddTransaction method.
		AddTransaction []struct {
			// Transaction is the transaction argument value.
			Transaction []byte
		}
		// GetBlocks holds details about calls to the GetBlocks method.
		GetBlocks []struct {
			// StartingBlockHeight is the startingBlockHeight argument value.
			StartingBlockHeight uint64
		}
		// GetFirstBlockTimestamp holds details about calls to the GetFirstBlockTimestamp method.
		GetFirstBlockTimestamp []struct {
		}
		// GetSettings holds details about calls to the GetSettings method.
		GetSettings []struct {
		}
		// GetTransactions holds details about calls to the GetTransactions method.
		GetTransactions []struct {
		}
		// GetUtxos holds details about calls to the GetUtxos method.
		GetUtxos []struct {
			// Address is the address argument value.
			Address string
		}
		// SendTargets holds details about calls to the SendTargets method.
		SendTargets []struct {
			// Targets is the targets argument value.
			Targets []string
		}
		// Target holds details about calls to the Target method.
		Target []struct {
		}
	}
	lockAddTransaction         sync.RWMutex
	lockGetBlocks              sync.RWMutex
	lockGetFirstBlockTimestamp sync.RWMutex
	lockGetSettings            sync.RWMutex
	lockGetTransactions        sync.RWMutex
	lockGetUtxos               sync.RWMutex
	lockSendTargets            sync.RWMutex
	lockTarget                 sync.RWMutex
}

// AddTransaction calls AddTransactionFunc.
func (mock *NeighborCallerMock) AddTransaction(transaction []byte) error {
	if mock.AddTransactionFunc == nil {
		panic("NeighborCallerMock.AddTransactionFunc: method is nil but NeighborCaller.AddTransaction was just called")
	}
	callInfo := struct {
		Transaction []byte
	}{
		Transaction: transaction,
	}
	mock.lockAddTransaction.Lock()
	mock.calls.AddTransaction = append(mock.calls.AddTransaction, callInfo)
	mock.lockAddTransaction.Unlock()
	return mock.AddTransactionFunc(transaction)
}

// AddTransactionCalls gets all the calls that were made to AddTransaction.
// Check the length with:
//
//	len(mockedNeighborCaller.AddTransactionCalls())
func (mock *NeighborCallerMock) AddTransactionCalls() []struct {
	Transaction []byte
} {
	var calls []struct {
		Transaction []byte
	}
	mock.lockAddTransaction.RLock()
	calls = mock.calls.AddTransaction
	mock.lockAddTransaction.RUnlock()
	return calls
}

// GetBlocks calls GetBlocksFunc.
func (mock *NeighborCallerMock) GetBlocks(startingBlockHeight uint64) ([]byte, error) {
	if mock.GetBlocksFunc == nil {
		panic("NeighborCallerMock.GetBlocksFunc: method is nil but NeighborCaller.GetBlocks was just called")
	}
	callInfo := struct {
		StartingBlockHeight uint64
	}{
		StartingBlockHeight: startingBlockHeight,
	}
	mock.lockGetBlocks.Lock()
	mock.calls.GetBlocks = append(mock.calls.GetBlocks, callInfo)
	mock.lockGetBlocks.Unlock()
	return mock.GetBlocksFunc(startingBlockHeight)
}

// GetBlocksCalls gets all the calls that were made to GetBlocks.
// Check the length with:
//
//	len(mockedNeighborCaller.GetBlocksCalls())
func (mock *NeighborCallerMock) GetBlocksCalls() []struct {
	StartingBlockHeight uint64
} {
	var calls []struct {
		StartingBlockHeight uint64
	}
	mock.lockGetBlocks.RLock()
	calls = mock.calls.GetBlocks
	mock.lockGetBlocks.RUnlock()
	return calls
}

// GetFirstBlockTimestamp calls GetFirstBlockTimestampFunc.
func (mock *NeighborCallerMock) GetFirstBlockTimestamp() (int64, error) {
	if mock.GetFirstBlockTimestampFunc == nil {
		panic("NeighborCallerMock.GetFirstBlockTimestampFunc: method is nil but NeighborCaller.GetFirstBlockTimestamp was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetFirstBlockTimestamp.Lock()
	mock.calls.GetFirstBlockTimestamp = append(mock.calls.GetFirstBlockTimestamp, callInfo)
	mock.lockGetFirstBlockTimestamp.Unlock()
	return mock.GetFirstBlockTimestampFunc()
}

// GetFirstBlockTimestampCalls gets all the calls that were made to GetFirstBlockTimestamp.
// Check the length with:
//
//	len(mockedNeighborCaller.GetFirstBlockTimestampCalls())
func (mock *NeighborCallerMock) GetFirstBlockTimestampCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetFirstBlockTimestamp.RLock()
	calls = mock.calls.GetFirstBlockTimestamp
	mock.lockGetFirstBlockTimestamp.RUnlock()
	return calls
}

// GetSettings calls GetSettingsFunc.
func (mock *NeighborCallerMock) GetSettings() ([]byte, error) {
	if mock.GetSettingsFunc == nil {
		panic("NeighborCallerMock.GetSettingsFunc: method is nil but NeighborCaller.GetSettings was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetSettings.Lock()
	mock.calls.GetSettings = append(mock.calls.GetSettings, callInfo)
	mock.lockGetSettings.Unlock()
	return mock.GetSettingsFunc()
}

// GetSettingsCalls gets all the calls that were made to GetSettings.
// Check the length with:
//
//	len(mockedNeighborCaller.GetSettingsCalls())
func (mock *NeighborCallerMock) GetSettingsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetSettings.RLock()
	calls = mock.calls.GetSettings
	mock.lockGetSettings.RUnlock()
	return calls
}

// GetTransactions calls GetTransactionsFunc.
func (mock *NeighborCallerMock) GetTransactions() ([]byte, error) {
	if mock.GetTransactionsFunc == nil {
		panic("NeighborCallerMock.GetTransactionsFunc: method is nil but NeighborCaller.GetTransactions was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetTransactions.Lock()
	mock.calls.GetTransactions = append(mock.calls.GetTransactions, callInfo)
	mock.lockGetTransactions.Unlock()
	return mock.GetTransactionsFunc()
}

// GetTransactionsCalls gets all the calls that were made to GetTransactions.
// Check the length with:
//
//	len(mockedNeighborCaller.GetTransactionsCalls())
func (mock *NeighborCallerMock) GetTransactionsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetTransactions.RLock()
	calls = mock.calls.GetTransactions
	mock.lockGetTransactions.RUnlock()
	return calls
}

// GetUtxos calls GetUtxosFunc.
func (mock *NeighborCallerMock) GetUtxos(address string) ([]byte, error) {
	if mock.GetUtxosFunc == nil {
		panic("NeighborCallerMock.GetUtxosFunc: method is nil but NeighborCaller.GetUtxos was just called")
	}
	callInfo := struct {
		Address string
	}{
		Address: address,
	}
	mock.lockGetUtxos.Lock()
	mock.calls.GetUtxos = append(mock.calls.GetUtxos, callInfo)
	mock.lockGetUtxos.Unlock()
	return mock.GetUtxosFunc(address)
}

// GetUtxosCalls gets all the calls that were made to GetUtxos.
// Check the length with:
//
//	len(mockedNeighborCaller.GetUtxosCalls())
func (mock *NeighborCallerMock) GetUtxosCalls() []struct {
	Address string
} {
	var calls []struct {
		Address string
	}
	mock.lockGetUtxos.RLock()
	calls = mock.calls.GetUtxos
	mock.lockGetUtxos.RUnlock()
	return calls
}

// SendTargets calls SendTargetsFunc.
func (mock *NeighborCallerMock) SendTargets(targets []string) error {
	if mock.SendTargetsFunc == nil {
		panic("NeighborCallerMock.SendTargetsFunc: method is nil but NeighborCaller.SendTargets was just called")
	}
	callInfo := struct {
		Targets []string
	}{
		Targets: targets,
	}
	mock.lockSendTargets.Lock()
	mock.calls.SendTargets = append(mock.calls.SendTargets, callInfo)
	mock.lockSendTargets.Unlock()
	return mock.SendTargetsFunc(targets)
}

// SendTargetsCalls gets all the calls that were made to SendTargets.
// Check the length with:
//
//	len(mockedNeighborCaller.SendTargetsCalls())
func (mock *NeighborCallerMock) SendTargetsCalls() []struct {
	Targets []string
} {
	var calls []struct {
		Targets []string
	}
	mock.lockSendTargets.RLock()
	calls = mock.calls.SendTargets
	mock.lockSendTargets.RUnlock()
	return calls
}

// Target calls TargetFunc.
func (mock *NeighborCallerMock) Target() string {
	if mock.TargetFunc == nil {
		panic("NeighborCallerMock.TargetFunc: method is nil but NeighborCaller.Target was just called")
	}
	callInfo := struct {
	}{}
	mock.lockTarget.Lock()
	mock.calls.Target = append(mock.calls.Target, callInfo)
	mock.lockTarget.Unlock()
	return mock.TargetFunc()
}

// TargetCalls gets all the calls that were made to Target.
// Check the length with:
//
//	len(mockedNeighborCaller.TargetCalls())
func (mock *NeighborCallerMock) TargetCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockTarget.RLock()
	calls = mock.calls.Target
	mock.lockTarget.RUnlock()
	return calls
}
