// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package clockmock

import (
	"github.com/my-cloud/ruthenium/src/clock"
	"sync"
)

// Ensure, that EngineMock does implement Engine.
// If this is not the case, regenerate this file with moq.
var _ clock.Engine = &EngineMock{}

// EngineMock is a mock implementation of Engine.
//
// 	func TestSomethingThatUsesEngine(t *testing.T) {
//
// 		// make and configure a mocked Engine
// 		mockedEngine := &EngineMock{
// 			DoFunc: func()  {
// 				panic("mock out the Do method")
// 			},
// 			StartFunc: func()  {
// 				panic("mock out the Start method")
// 			},
// 			StopFunc: func()  {
// 				panic("mock out the Stop method")
// 			},
// 		}
//
// 		// use mockedEngine in code that requires Engine
// 		// and then make assertions.
//
// 	}
type EngineMock struct {
	// DoFunc mocks the Do method.
	DoFunc func()

	// StartFunc mocks the Start method.
	StartFunc func()

	// StopFunc mocks the Stop method.
	StopFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// Do holds details about calls to the Do method.
		Do []struct {
		}
		// Start holds details about calls to the Start method.
		Start []struct {
		}
		// Stop holds details about calls to the Stop method.
		Stop []struct {
		}
	}
	lockDo    sync.RWMutex
	lockStart sync.RWMutex
	lockStop  sync.RWMutex
}

// Do calls DoFunc.
func (mock *EngineMock) Do() {
	if mock.DoFunc == nil {
		panic("EngineMock.DoFunc: method is nil but Engine.Do was just called")
	}
	callInfo := struct {
	}{}
	mock.lockDo.Lock()
	mock.calls.Do = append(mock.calls.Do, callInfo)
	mock.lockDo.Unlock()
	mock.DoFunc()
}

// DoCalls gets all the calls that were made to Do.
// Check the length with:
//     len(mockedEngine.DoCalls())
func (mock *EngineMock) DoCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockDo.RLock()
	calls = mock.calls.Do
	mock.lockDo.RUnlock()
	return calls
}

// Start calls StartFunc.
func (mock *EngineMock) Start() {
	if mock.StartFunc == nil {
		panic("EngineMock.StartFunc: method is nil but Engine.Start was just called")
	}
	callInfo := struct {
	}{}
	mock.lockStart.Lock()
	mock.calls.Start = append(mock.calls.Start, callInfo)
	mock.lockStart.Unlock()
	mock.StartFunc()
}

// StartCalls gets all the calls that were made to Start.
// Check the length with:
//     len(mockedEngine.StartCalls())
func (mock *EngineMock) StartCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockStart.RLock()
	calls = mock.calls.Start
	mock.lockStart.RUnlock()
	return calls
}

// Stop calls StopFunc.
func (mock *EngineMock) Stop() {
	if mock.StopFunc == nil {
		panic("EngineMock.StopFunc: method is nil but Engine.Stop was just called")
	}
	callInfo := struct {
	}{}
	mock.lockStop.Lock()
	mock.calls.Stop = append(mock.calls.Stop, callInfo)
	mock.lockStop.Unlock()
	mock.StopFunc()
}

// StopCalls gets all the calls that were made to Stop.
// Check the length with:
//     len(mockedEngine.StopCalls())
func (mock *EngineMock) StopCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockStop.RLock()
	calls = mock.calls.Stop
	mock.lockStop.RUnlock()
	return calls
}
