// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package logtest

import (
	"github.com/my-cloud/ruthenium/src/log"
	"sync"
)

// Ensure, that LoggerMock does implement Logger.
// If this is not the case, regenerate this file with moq.
var _ log.Logger = &LoggerMock{}

// LoggerMock is a mock implementation of Logger.
//
// 	func TestSomethingThatUsesLogger(t *testing.T) {
//
// 		// make and configure a mocked Logger
// 		mockedLogger := &LoggerMock{
// 			DebugFunc: func(msg string)  {
// 				panic("mock out the Debug method")
// 			},
// 			ErrorFunc: func(msg string)  {
// 				panic("mock out the Error method")
// 			},
// 			InfoFunc: func(msg string)  {
// 				panic("mock out the Info method")
// 			},
// 			WarnFunc: func(msg string)  {
// 				panic("mock out the Warn method")
// 			},
// 		}
//
// 		// use mockedLogger in code that requires Logger
// 		// and then make assertions.
//
// 	}
type LoggerMock struct {
	// DebugFunc mocks the Debug method.
	DebugFunc func(msg string)

	// ErrorFunc mocks the Error method.
	ErrorFunc func(msg string)

	// InfoFunc mocks the Info method.
	InfoFunc func(msg string)

	// WarnFunc mocks the Warn method.
	WarnFunc func(msg string)

	// calls tracks calls to the methods.
	calls struct {
		// Debug holds details about calls to the Debug method.
		Debug []struct {
			// Msg is the msg argument value.
			Msg string
		}
		// Error holds details about calls to the Error method.
		Error []struct {
			// Msg is the msg argument value.
			Msg string
		}
		// Info holds details about calls to the Info method.
		Info []struct {
			// Msg is the msg argument value.
			Msg string
		}
		// Warn holds details about calls to the Warn method.
		Warn []struct {
			// Msg is the msg argument value.
			Msg string
		}
	}
	lockDebug sync.RWMutex
	lockError sync.RWMutex
	lockInfo  sync.RWMutex
	lockWarn  sync.RWMutex
}

func NewLoggerMock() *LoggerMock {
	logger := new(LoggerMock)
	logger.DebugFunc = func(string) {}
	logger.InfoFunc = func(string) {}
	logger.WarnFunc = func(string) {}
	logger.ErrorFunc = func(string) {}
	return logger
}

// Debug calls DebugFunc.
func (mock *LoggerMock) Debug(msg string) {
	if mock.DebugFunc == nil {
		panic("LoggerMock.DebugFunc: method is nil but Logger.Debug was just called")
	}
	callInfo := struct {
		Msg string
	}{
		Msg: msg,
	}
	mock.lockDebug.Lock()
	mock.calls.Debug = append(mock.calls.Debug, callInfo)
	mock.lockDebug.Unlock()
	mock.DebugFunc(msg)
}

// DebugCalls gets all the calls that were made to Debug.
// Check the length with:
//     len(mockedLogger.DebugCalls())
func (mock *LoggerMock) DebugCalls() []struct {
	Msg string
} {
	var calls []struct {
		Msg string
	}
	mock.lockDebug.RLock()
	calls = mock.calls.Debug
	mock.lockDebug.RUnlock()
	return calls
}

// Error calls ErrorFunc.
func (mock *LoggerMock) Error(msg string) {
	if mock.ErrorFunc == nil {
		panic("LoggerMock.ErrorFunc: method is nil but Logger.Error was just called")
	}
	callInfo := struct {
		Msg string
	}{
		Msg: msg,
	}
	mock.lockError.Lock()
	mock.calls.Error = append(mock.calls.Error, callInfo)
	mock.lockError.Unlock()
	mock.ErrorFunc(msg)
}

// ErrorCalls gets all the calls that were made to Error.
// Check the length with:
//     len(mockedLogger.ErrorCalls())
func (mock *LoggerMock) ErrorCalls() []struct {
	Msg string
} {
	var calls []struct {
		Msg string
	}
	mock.lockError.RLock()
	calls = mock.calls.Error
	mock.lockError.RUnlock()
	return calls
}

// Info calls InfoFunc.
func (mock *LoggerMock) Info(msg string) {
	if mock.InfoFunc == nil {
		panic("LoggerMock.InfoFunc: method is nil but Logger.Info was just called")
	}
	callInfo := struct {
		Msg string
	}{
		Msg: msg,
	}
	mock.lockInfo.Lock()
	mock.calls.Info = append(mock.calls.Info, callInfo)
	mock.lockInfo.Unlock()
	mock.InfoFunc(msg)
}

// InfoCalls gets all the calls that were made to Info.
// Check the length with:
//     len(mockedLogger.InfoCalls())
func (mock *LoggerMock) InfoCalls() []struct {
	Msg string
} {
	var calls []struct {
		Msg string
	}
	mock.lockInfo.RLock()
	calls = mock.calls.Info
	mock.lockInfo.RUnlock()
	return calls
}

// Warn calls WarnFunc.
func (mock *LoggerMock) Warn(msg string) {
	if mock.WarnFunc == nil {
		panic("LoggerMock.WarnFunc: method is nil but Logger.Warn was just called")
	}
	callInfo := struct {
		Msg string
	}{
		Msg: msg,
	}
	mock.lockWarn.Lock()
	mock.calls.Warn = append(mock.calls.Warn, callInfo)
	mock.lockWarn.Unlock()
	mock.WarnFunc(msg)
}

// WarnCalls gets all the calls that were made to Warn.
// Check the length with:
//     len(mockedLogger.WarnCalls())
func (mock *LoggerMock) WarnCalls() []struct {
	Msg string
} {
	var calls []struct {
		Msg string
	}
	mock.lockWarn.RLock()
	calls = mock.calls.Warn
	mock.lockWarn.RUnlock()
	return calls
}
