// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package networktest

import (
	"context"
	gp2p "github.com/leprosus/golang-p2p"
	"github.com/my-cloud/ruthenium/src/node/network"
	"sync"
)

// Ensure, that HandlerMock does implement Handler.
// If this is not the case, regenerate this file with moq.
var _ network.Handler = &HandlerMock{}

// HandlerMock is a mock implementation of Handler.
//
//	func TestSomethingThatUsesHandler(t *testing.T) {
//
//		// make and configure a mocked Handler
//		mockedHandler := &HandlerMock{
//			HandleFunc: func(contextMoqParam context.Context, req gp2p.Data) (gp2p.Data, error) {
//				panic("mock out the Handle method")
//			},
//		}
//
//		// use mockedHandler in code that requires Handler
//		// and then make assertions.
//
//	}
type HandlerMock struct {
	// HandleFunc mocks the Handle method.
	HandleFunc func(contextMoqParam context.Context, req gp2p.Data) (gp2p.Data, error)

	// calls tracks calls to the methods.
	calls struct {
		// Handle holds details about calls to the Handle method.
		Handle []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Req is the req argument value.
			Req gp2p.Data
		}
	}
	lockHandle sync.RWMutex
}

// Handle calls HandleFunc.
func (mock *HandlerMock) Handle(contextMoqParam context.Context, req gp2p.Data) (gp2p.Data, error) {
	if mock.HandleFunc == nil {
		panic("HandlerMock.HandleFunc: method is nil but Handler.Handle was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		Req             gp2p.Data
	}{
		ContextMoqParam: contextMoqParam,
		Req:             req,
	}
	mock.lockHandle.Lock()
	mock.calls.Handle = append(mock.calls.Handle, callInfo)
	mock.lockHandle.Unlock()
	return mock.HandleFunc(contextMoqParam, req)
}

// HandleCalls gets all the calls that were made to Handle.
// Check the length with:
//
//	len(mockedHandler.HandleCalls())
func (mock *HandlerMock) HandleCalls() []struct {
	ContextMoqParam context.Context
	Req             gp2p.Data
} {
	var calls []struct {
		ContextMoqParam context.Context
		Req             gp2p.Data
	}
	mock.lockHandle.RLock()
	calls = mock.calls.Handle
	mock.lockHandle.RUnlock()
	return calls
}
