// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package clock

import (
	"github.com/my-cloud/ruthenium/src/clock"
	"sync"
	"time"
)

// Ensure, that WatchMock does implement Watch.
// If this is not the case, regenerate this file with moq.
var _ clock.Watch = &WatchMock{}

// WatchMock is a mock implementation of Watch.
//
// 	func TestSomethingThatUsesWatch(t *testing.T) {
//
// 		// make and configure a mocked Watch
// 		mockedWatch := &WatchMock{
// 			NowFunc: func() time.Time {
// 				panic("mock out the Now method")
// 			},
// 		}
//
// 		// use mockedWatch in code that requires Watch
// 		// and then make assertions.
//
// 	}
type WatchMock struct {
	// NowFunc mocks the Now method.
	NowFunc func() time.Time

	// calls tracks calls to the methods.
	calls struct {
		// Now holds details about calls to the Now method.
		Now []struct {
		}
	}
	lockNow sync.RWMutex
}

// Now calls NowFunc.
func (mock *WatchMock) Now() time.Time {
	if mock.NowFunc == nil {
		panic("WatchMock.NowFunc: method is nil but Watch.Now was just called")
	}
	callInfo := struct {
	}{}
	mock.lockNow.Lock()
	mock.calls.Now = append(mock.calls.Now, callInfo)
	mock.lockNow.Unlock()
	return mock.NowFunc()
}

// NowCalls gets all the calls that were made to Now.
// Check the length with:
//     len(mockedWatch.NowCalls())
func (mock *WatchMock) NowCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockNow.RLock()
	calls = mock.calls.Now
	mock.lockNow.RUnlock()
	return calls
}
