name: Build

on:
  push:
    branches: [ "main", "release/*" ]
  pull_request:
    branches: [ "main", "release/*" ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
    - name: Build
      run: go build -v ./...
