name: Quality

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
    - name: Test
      run: go test -v -coverpkg=./... ./... -coverprofile=coverage.out
    - name: Upload coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage ${{ matrix.node-version }}
        path: ${{ github.workspace }}/test/coverage.out
  scan:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Download coverage
      uses: actions/download-artifact@v3
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
