name: Release

# Workflow will run when all workflows are successful on the release branch
on:
  workflow_run:
    workflows: [ Go ]
    types: 
      - completed

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
