name: Release

# Workflow will run when all workflows are successful on the release branch
on:
  push:
    branches: [ "main", "44-automatically-release" ]


jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
