name: Release

on:
  push:
    branches: [ "main", "101-automatically-deploy-a-package-on-release" ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: go-semantic-release/action@v1
        with:
          ssh-key: ${{ secrets.RELEASE_BOT_KEY }}
